-- ==========================================
-- 1. Информация о пользователях
-- ==========================================
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email)
);

-- ==========================================
-- 2. Информация о запросах вещи
-- ==========================================
CREATE TABLE IF NOT EXISTS requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_users FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ==========================================
-- 3. Информация о вещах
-- ==========================================
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT fk_items_users FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ==========================================
-- 4. Комментарии
-- ==========================================
CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(512)                            NOT NULL,
    user_id BIGINT                                  NOT NULL,
    item_id BIGINT                                  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_bookings_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_items FOREIGN KEY (item_id) REFERENCES items (id)
);

-- ==========================================
-- 5. Информация о бронировании
-- ==========================================
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    booker     BIGINT                                  NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    status     VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_users FOREIGN KEY (booker) REFERENCES users (id),
    CONSTRAINT fk_bookings_items FOREIGN KEY (item_id) REFERENCES items (id)
);